# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCorge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('grault', models.CharField(max_length=50, verbose_name='Grault')),
                ('thud', models.IntegerField(verbose_name='Thud')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseFoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('subject', models.CharField(max_length=70, verbose_name=b'Subject')),
                ('bar', models.CharField(max_length=200, verbose_name='Bar')),
                ('baz', models.CharField(choices=[('CR', 'Corge'), ('WL', 'Waldo')], max_length=30, verbose_name='Baz')),
                ('qux', models.TextField(blank=True, verbose_name='Qux')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
