# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefoo',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
        migrations.AddField(
            model_name='casecorge',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
    ]
